INPUT_DATA_PATH ="../data/"
ANIO_INICIAL_ANALISIS_ANUAL = 2014
ANIO_FINAL_ANALISIS_ANUAL = 2022
DEMANDA_SIN_FILE_NAME=INPUT_DATA_PATH+"DemandaSIN"
DEMANDA_COMERCIAL_TOTAL_AGENTE_FILE_NAME= INPUT_DATA_PATH+"DemTotXAge"
DEMANDA_COMERCIAL_NO_REGULADA_AGENTE_FILE_NAME = INPUT_DATA_PATH+"DemComXAgeNOReg"
DEMANDA_COMERCIAL_REGULADA_AGENTE_FILE_NAME = INPUT_DATA_PATH+"DemComXAgeReg"

from enum import Enum
class ConsultasXMEnum(Enum):
    DEMANDA_COMERCIAL_REGULADA_OPC = 1
    DEMANDA_COMERCIAL_NO_REGULADA_OPC = 2
    DEMANDA_SIN_OPC = 3
    DEMANDA_TOTAL_AGENTES_OPC = 4
    LISTADO_METRICAS_OPC = 5
    LISTADO_AGENTES_OPC = 6